# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_check_args: "--no-vignettes"
warnings_are_errors: false

branches:
  only:
    - "experimental"

r_packages:
  - covr
  - devtools  # explicitly named temp fix for #2801
  - data.table
  - stringr
  - tidyverse

after_success:
- Rscript -e 'covr::codecov()'