# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_check_args: "--no-vignettes"
warnings_are_errors: true

branches:
  only:
    - "master"

r_packages:
  - covr

after_success:
- Rscript -e 'covr::codecov()'